#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.4.12f1_59ddc4c59b4f"
#define UNITY_VERSION_FULL_NICE "2018.4.12f1 (59ddc4c59b4f)"
#define UNITY_VERSION_BLD 5889476
#define UNITY_VERSION_DATE 1571736098
#define UNITY_VERSION_WIN "2018.4.12.5889476"
#define UNITY_VERSION_BRANCH "2018.4/release"
